import './globals.css';

export const metadata = {
      title: 'Next.js',
      description: 'Generated by Next.js',
}

export default function RootLayout({
      children,
}: {
      children: React.ReactNode
}) {
      return (
            <html lang="en">

                  <body>
                        <header className='flex justify-center items-center h-10 bg-blue-500'>
                              <h1>Eyow</h1>
                        </header>


                        {children}

                        <footer className='flex justify-center items-center h-10 bg-blue-500'> eabab </footer>

                  </body>
            </html>
      )
}
